### ISSUE TITLE
how to Upgrade

### ISSUE THREAD

**Issue by wandelson** [IdentityServer/Thinktecture.IdentityServer2#839]
how to Upgrade
identityServer to identityServer 3?

**Comment by brockallen** [comment]
We don't have an upgrade path. Mainly because the fundamental protocol(s) being supported is different.

**Comment by wandelson** [comment]
is complex upgrade?

**Comment by brockallen** [comment]
It's a new server and a new protocol. I'd say "yes".

**Comment by wandelson** [comment]
ok. thanks
